# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#eeefff", bold = true }
tab_inactive = { fg = "#dce1ff", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff71e3", bg = "#ff71e3" }
marker_cut = { fg = "#ffd7f7", bg = "#ffd7f7" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#ffeaf8", bg = "#ffeaf8" }

# Count
count_copied = { fg = "#000000", bg = "#ffd7f7" }
count_cut = { fg = "#000000", bg = "#ffd7f7" }
count_selected = { fg = "#000000", bg = "#ffeaf8" }

# Border
border_symbol = "│"
border_style  = { fg = "#b5c4ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#eeefff", fg = "#000000", bold = true }
normal_alt  = { bg = "#45464f", fg = "#ffffff" }

# Select mode
select_main = { bg = "#eeefff", fg = "#000000", bold = true }
select_alt  = { bg = "#45464f", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#ffeaf8", fg = "#000000", bold = true }
unset_alt  = { bg = "#45464f", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#eeefff", bg = "#4f5056" }
progress_error = { fg = "#ffece9", bg = "#4f5056" }

# Permissions
permissions_t = { fg = "#555fff" }
permissions_w = { fg = "#ff51c5" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#ff3ed8" }
permissions_s = { fg = "#435eff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#eeefff" }
active = { fg = "#ffeaf8", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#eeefff" }
value = { fg = "#ffffff" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#eeefff", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#eeefff" }
title = {}
hovered = { fg = "#ffd7f7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#4f5056" }
cand = { fg = "#eeefff" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#eeefff" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffeaf8" }
title_warn = { fg = "#eeefff" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#b5c4ff" },
]

# : ]]]
