[config]
# ...

[templates.hyprland]
input_path = '~/.config/matugen/templates/nvim-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-color.conf'
output_path = '~/.config/kitty/kitty.conf'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-colors2.lua'
output_path = "~/.config/nvim/colors/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'
