--[[
-- Lua Colors
-- Generated with Matugen
--]]

local Colors = {
      background = "#121317",
      error = "#ffb4ab",
      error_container = "#93000a",
      inverse_on_surface = "#2f3034",
      inverse_primary = "#435e8e",
      inverse_surface = "#e3e2e6",
      on_background = "#e3e2e6",
      on_error = "#690005",
      on_error_container = "#ffdad6",
      on_primary = "#10305d",
      on_primary_container = "#d7e3ff",
      on_primary_fixed = "#001b3f",
      on_primary_fixed_variant = "#2b4775",
      on_secondary = "#273043",
      on_secondary_container = "#d9e2fb",
      on_secondary_fixed = "#121c2d",
      on_secondary_fixed_variant = "#3d475a",
      on_surface = "#e3e2e6",
      on_surface_variant = "#c4c6d0",
      on_tertiary = "#48214c",
      on_tertiary_container = "#ffd6fc",
      on_tertiary_fixed = "#310a35",
      on_tertiary_fixed_variant = "#613764",
      outline = "#8e909a",
      outline_variant = "#44474f",
      primary = "#acc7fd",
      primary_container = "#2b4775",
      primary_fixed = "#d7e3ff",
      primary_fixed_dim = "#acc7fd",
      scrim = "#000000",
      secondary = "#bdc6de",
      secondary_container = "#3d475a",
      secondary_fixed = "#d9e2fb",
      secondary_fixed_dim = "#bdc6de",
      shadow = "#000000",
      surface = "#121317",
      surface_bright = "#38393d",
      surface_container = "#1e1f23",
      surface_container_high = "#292a2d",
      surface_container_highest = "#343538",
      surface_container_low = "#1a1b1f",
      surface_container_lowest = "#0d0e11",
      surface_dim = "#121317",
      surface_tint = "#acc7fd",
      surface_variant = "#44474f",
      tertiary = "#ebb5ea",
      tertiary_container = "#613764",
      tertiary_fixed = "#ffd6fc",
      tertiary_fixed_dim = "#ebb5ea",
}

return Colors
